runtime: php
php_version: 8.1  # or 8.2 if 8.1 doesn't work

build:
  # This section is used for the build process
  commands:
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan storage:link

start:
  # This section specifies how to start the app
  command: php artisan serve --host=0.0.0.0 --port=$PORT

env:
  # Define environment variables here
  APP_KEY: "base64:C0Srvjhmm04HUCAbXzkmU+73nTvAQpKpXSEfbKBp8jY="
  DB_CONNECTION: mysql
  DB_HOST: $MYSQLHOST
  DB_PORT: 3306
  DB_DATABASE: $MYSQLDATABASE
  DB_USERNAME: $MYSQLUSER
  DB_PASSWORD: $MYSQLPASSWORD
  APP_URL: "http://$RAILWAY_STATIC_URL"   # This will be your Railway app URL (if it's set)

  # You can add more environment variables as needed, like MAIL, etc.
