name: my-laravel-app
services:
  - name: app
    build:
      # Use the custom build file if needed
      commands:
        - composer install --no-dev --optimize-autoloader
    environment:
      - APP_KEY=${APP_KEY}
    env:
      DATABASE_URL: ${MYSQL_URL}
    web:
      # Ensure Laravel is set to run with PHP-FPM
      command: "php artisan serve --host=0.0.0.0 --port=$PORT"
    regions:
      - dfw
    routes:
      - path: /
